### ISSUE TITLE
New API specification

### ISSUE THREAD

**Issue by Maistho** [JPatricio/tddd97_lab2_testsuite#2]
I think that the API specification should be completely remade.

Instead of having routes like:

`/get_user_data_by_token`

We should have:

`/api/v1/users/:username`

I could write up a new specification following a similar style instead.

**Comment by Maistho** [comment]
In addition to this, I would prefer using HTTP Headers for sending the token.

Probably in the Authorization header:
`Authorization: Bearer mytoken`

**Comment by JPatricio** [comment]
That does look much better. Although, we might want to run it through Sahand before committing to that approach.

Regarding the HTTP header use. I agree but I also think that we should not have requirements/assumptions in the tests that are not explicitly mentioned in the lab description, hence, until it becomes a requirement, there should probably be a test for either scenario.

**Comment by Maistho** [comment]
My plan is to rewrite the lab at the same time as writing these tests.

Pretty much the only requirement of the lab should be: "Passes all the tests"
